# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

# A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
# with the app.
name: api

# The runtime the application uses.
# Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
type: php:8.2

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
# More information: https://docs.platform.sh/create-apps/app-reference.html#relationships
relationships:
  database: "database:postgresql"

# The size of the persistent disk of the application (in MB). Minimum value is 128.
disk: 2048

# Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
# More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
mounts:
  "/var/cache": "shared:files/cache"
  "/var/log": "shared:files/log"
  "/var/sessions": "shared:files/sessions"

# The web key configures the web server running in front of your app.
# More information: https://docs.platform.sh/create-apps/app-reference.html#web
web:
  locations:
    "/":
      passthru: "/index.php"
      root: "public"
      index:
        - index.php
      scripts: true
      allow: true
      headers:
        Access-Control-Allow-Origin: "*"

# Define variables used by this app (env, runtime settings, ...)
# https://docs.platform.sh/create-apps/app-reference.html#variables
variables:
  env:
    # ensure that assets won't be built as they are already committed.
    APP_ENV: 'prod'
  php:
    assert.active: off

# Specifies a default set of build tasks to run. Flavors are language-specific.
# More information: https://docs.platform.sh/create-apps/app-reference.html#build
build:
  flavor: composer

# Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
# are available in the PATH during the build process and in the runtime environment. They’re installed before
# the build hook runs using a package manager for the language.
# More information: https://docs.platform.sh/create-apps/app-reference.html#dependencies
dependencies:
  php:
    composer/composer: "^2"

# Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
# More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
hooks:
  build: |
    set -x -e
    
    curl -s https://get.symfony.com/cloud/configurator | bash
    symfony-build
  deploy: |
    set -x -e
    
    symfony-deploy

# Scheduled tasks for the app.
# More information: https://docs.platform.sh/create-apps/app-reference.html#crons
crons:
  update-sighting:
    spec: '*/5 * * * *'
    cmd: './bin/console app:update-sighting-scores'

# Customizations to your PHP or Lisp runtime.
# More information: https://docs.platform.sh/create-apps/app-reference.html#runtime
runtime:
  extensions:
    - ctype
    - iconv
    - apcu
    - mbstring
    - sodium
    - xsl
    - pdo_pgsql
